{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "custom-workbench.secret.quay" . }}
  namespace: {{ include "custom-workbench.rhoaiNamespace" . }}
  labels:
    {{- include "custom-workbench.labels" . | nindent 4 }}
    app: {{ .Values.rhoai.imageName }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.secrets.quay.server .Values.secrets.quay.username .Values.secrets.quay.password (printf "%s:%s" .Values.secrets.quay.username .Values.secrets.quay.password | b64enc) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "custom-workbench.secret.githubPat" . }}
  namespace: {{ include "custom-workbench.rhoaiNamespace" . }}
  labels:
    {{- include "custom-workbench.labels" . | nindent 4 }}
    app: {{ .Values.rhoai.imageName }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.secrets.github.patUsername | quote }}
  password: {{ .Values.secrets.github.pat | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "custom-workbench.secret.webhook" . }}
  namespace: {{ include "custom-workbench.rhoaiNamespace" . }}
  labels:
    {{- include "custom-workbench.labels" . | nindent 4 }}
    app: {{ .Values.rhoai.imageName }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  WebHookSecretKey: {{ .Values.secrets.github.webhookSecret | quote }}
{{- end }}
