{{- if .Values.tekton.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tekton.serviceAccount }}
  namespace: {{ include "custom-workbench.rhoaiNamespace" . }}
  labels:
    app: {{ .Values.rhoai.imageName }}
    {{- include "custom-workbench.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.tekton.serviceAccount }}-edit
  namespace: {{ include "custom-workbench.rhoaiNamespace" . }}
  labels:
    app: {{ .Values.rhoai.imageName }}
    {{- include "custom-workbench.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ .Values.tekton.serviceAccount }}
    namespace: {{ include "custom-workbench.rhoaiNamespace" . }}
{{- end }}
