{{- if and .Values.workbench.enabled (eq (include "custom-workbench.workbenchGitSecretCreate" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "custom-workbench.workbenchGitSecret" . }}
  namespace: {{ include "custom-workbench.workbenchNamespace" . }}
  labels:
    {{- include "custom-workbench.labels" . | nindent 4 }}
    app: {{ .Values.workbench.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  .git-credentials: {{ printf "https://%s:%s@%s" (include "custom-workbench.workbenchGitUsername" .) .Values.secrets.github.pat .Values.workbench.gitCredentials.gitHost | quote }}
  .gitconfig: |
    [credential]
        helper = store --file /opt/app-root/src/.git-credentials
    [user]
        name = {{ include "custom-workbench.workbenchGitUsername" . }}
        email = {{ include "custom-workbench.workbenchGitUsername" . }}@users.noreply.github.com
{{- end }}
