{{- if .Values.workbench.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workbench.name }}
  namespace: {{ include "custom-workbench.workbenchNamespace" . }}
  labels:
    opendatahub.io/dashboard: "true"
    {{- include "custom-workbench.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.workbench.pvc.storage }}
{{- end }}
